version: "3.8"
name: "sneakers-ml"
services:
  bot:
    container_name: sneakers-ml-bot
    build:
      context: .
      dockerfile: deploy/bot/Dockerfile
    restart: always
    environment:
      - API_HOST=http://api:8000
  api:
    container_name: sneakers-ml-api
    build:
      context: .
      dockerfile: deploy/app/Dockerfile
    restart: always
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - REDIS_HOST=redis
  redis:
    container_name: sneakers-ml-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
