name: Build api docker image

on:
  push:
    branches:
      - trunk
    tags: ["v*.*.*"]
  pull_request:

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Yandex Cloud Container Registry
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deploy/app/Dockerfile  
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            cr.yandex/crp9sd2f3p1o3mfu9664/sneakers-ml-api:latest
            cr.yandex/crp9sd2f3p1o3mfu9664/sneakers-ml-api:${{ env.IMAGE_TAG }}
            ghcr.io/user/app:latest
            ghcr.io/user/app:${{ env.IMAGE_TAG }}
